name: API CI Develop

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: npm run build
    
  build:
    needs: ci
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the image
      run: |
        docker build . --tag ghcr.io/ralvescostati/node_base:latest
        docker run ghcr.io/ralvescostati/node_base:latest
        docker push ghcr.io/ralvescostati/node_base:latest

  deploy_dev:
    needs: build
    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Dev
      run: echo "Deployed :)"
  
  deploy_prod:
    needs: build
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Prod
      run: echo "Deployed :)." 

